import {
  Type, Binary, Ruler, Calculator, Sparkles, Globe, BrainCircuit,
  AlignLeft, CaseSensitive, FileText, ArrowLeftRight, ListFilter, Eraser,
  Braces, ArrowDownToLine, Link2, Key, Hash, Fingerprint, Palette, Code2,
  Binary as BinIcon, BookOpen, Clock, Activity, Landmark, Receipt, TrendingUp,
  QrCode, KeyRound, Paintbrush, Tags, Share2, Bot,
  Wand2, SpellCheck, PenLine, Languages,
} from "lucide-react";
import type { Tool, ToolCategory } from "./types";

import { WordCounter } from "@/components/tools/WordCounter";
import { CaseConverter } from "@/components/tools/CaseConverter";
import { LoremIpsum } from "@/components/tools/LoremIpsum";
import { TextReverser } from "@/components/tools/TextReverser";
import { RemoveDuplicateLines } from "@/components/tools/RemoveDuplicateLines";
import { WhitespaceCleaner } from "@/components/tools/WhitespaceCleaner";
import { JsonFormatter } from "@/components/tools/JsonFormatter";
import { Base64Encoder } from "@/components/tools/Base64Encoder";
import { UrlEncoder } from "@/components/tools/UrlEncoder";
import { JwtDecoder } from "@/components/tools/JwtDecoder";
import { HashGenerator } from "@/components/tools/HashGenerator";
import { UuidGenerator } from "@/components/tools/UuidGenerator";
import { ColorConverter } from "@/components/tools/ColorConverter";
import { HtmlEntityEncoder } from "@/components/tools/HtmlEntityEncoder";
import { NumberBaseConverter } from "@/components/tools/NumberBaseConverter";
import { UnitConverter } from "@/components/tools/UnitConverter";
import { RomanNumeralConverter } from "@/components/tools/RomanNumeralConverter";
import { CsvJsonConverter } from "@/components/tools/CsvJsonConverter";
import { TimestampConverter } from "@/components/tools/TimestampConverter";
import { PercentageCalculator } from "@/components/tools/PercentageCalculator";
import { AgeCalculator } from "@/components/tools/AgeCalculator";
import { BmiCalculator } from "@/components/tools/BmiCalculator";
import { LoanCalculator } from "@/components/tools/LoanCalculator";
import { TipCalculator } from "@/components/tools/TipCalculator";
import { CompoundInterestCalculator } from "@/components/tools/CompoundInterestCalculator";
import { QrCodeGenerator } from "@/components/tools/QrCodeGenerator";
import { PasswordGenerator } from "@/components/tools/PasswordGenerator";
import { ColorPaletteGenerator } from "@/components/tools/ColorPaletteGenerator";
import { GradientGenerator } from "@/components/tools/GradientGenerator";
import { MetaTagGenerator } from "@/components/tools/MetaTagGenerator";
import { OpenGraphGenerator } from "@/components/tools/OpenGraphGenerator";
import { RobotsTxtGenerator } from "@/components/tools/RobotsTxtGenerator";
import { AiSummarizer } from "@/components/tools/AiSummarizer";
import { AiGrammar } from "@/components/tools/AiGrammar";
import { AiRewriter } from "@/components/tools/AiRewriter";
import { AiTranslator } from "@/components/tools/AiTranslator";
import { AiCodeExplainer } from "@/components/tools/AiCodeExplainer";

export const categories: ToolCategory[] = [
  {
    slug: "text",
    name: "Text",
    tagline: "Clean, transform, and analyze text instantly",
    icon: Type,
    accent: "#7ab566",
  },
  {
    slug: "developer",
    name: "Developer",
    tagline: "Format, encode, decode, and inspect common formats",
    icon: Binary,
    accent: "#64748b",
  },
  {
    slug: "converters",
    name: "Converters",
    tagline: "Switch between bases, units, and formats",
    icon: Ruler,
    accent: "#0ea5e9",
  },
  {
    slug: "calculators",
    name: "Calculators",
    tagline: "Quick math for everyday life and finance",
    icon: Calculator,
    accent: "#f59e0b",
  },
  {
    slug: "generators",
    name: "Generators",
    tagline: "Create passwords, QR codes, palettes, and more",
    icon: Sparkles,
    accent: "#8b5cf6",
  },
  {
    slug: "web-seo",
    name: "Web & SEO",
    tagline: "Build the tags and files that drive discovery",
    icon: Globe,
    accent: "#10b981",
  },
  {
    slug: "ai",
    name: "AI",
    tagline: "Summarize, rewrite, translate, and explain code",
    icon: BrainCircuit,
    accent: "#a855f7",
  },
];

const FAQ_TEXT = [
  { q: "Are these tools free to use?", a: "Yes — every Toolly tool is free, with no sign-up required. You can use them as often as you like." },
  { q: "Do my texts or files leave my browser?", a: "For all client-side tools (the majority), processing happens entirely in your browser. For AI tools, your text is sent to our AI endpoint only long enough to process and return the result; we do not store it." },
];

export const tools: Tool[] = [
  // ───────── Text ─────────
  {
    slug: "word-counter",
    name: "Word Counter",
    short: "Live words, characters, sentences, reading time",
    description: "Count words, characters, sentences, paragraphs, and reading time in real time as you type.",
    category: "text",
    icon: AlignLeft,
    component: WordCounter,
    isPopular: true,
    featured: true,
    keywords: ["word count", "character count", "reading time", "text analyzer"],
    related: ["case-converter", "whitespace-cleaner", "remove-duplicate-lines"],
    howToUse: ["Type or paste your text into the input box.", "All counts update instantly — no button to click.", "Use Copy or Download to save the text when you're done."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    short: "UPPER, lower, Title, camelCase, snake_case, kebab",
    description: "Convert text between 10 cases including UPPER, lower, Title, camelCase, PascalCase, snake_case, kebab-case, and CONSTANT_CASE.",
    category: "text",
    icon: CaseSensitive,
    component: CaseConverter,
    keywords: ["uppercase", "lowercase", "title case", "camel case", "snake case", "kebab case"],
    related: ["word-counter", "whitespace-cleaner", "text-reverser"],
    howToUse: ["Paste your text in the input box.", "Pick a target case from the list.", "The output updates instantly and can be copied."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    short: "Placeholder text for designs and mockups",
    description: "Generate classic Lorem Ipsum placeholder text with configurable paragraphs and sentences.",
    category: "text",
    icon: FileText,
    component: LoremIpsum,
    keywords: ["lorem ipsum", "placeholder text", "dummy text", "filler text"],
    related: ["word-counter", "case-converter"],
    howToUse: ["Choose the number of paragraphs and sentences per paragraph.", "Optionally start with the classic 'Lorem ipsum…' opening.", "Click Generate and copy the result."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "text-reverser",
    name: "Text Reverser",
    short: "Reverse characters, words, lines, or flip upside-down",
    description: "Reverse a string by characters, words, or lines — or flip it upside-down using Unicode glyphs.",
    category: "text",
    icon: ArrowLeftRight,
    component: TextReverser,
    keywords: ["reverse text", "backwards text", "flip text", "reverse string"],
    related: ["case-converter", "whitespace-cleaner"],
    howToUse: ["Paste your text.", "Pick a reversal mode (chars, words, lines, or flip).", "Output updates live."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    short: "Dedupe, find duplicates, or sort lines",
    description: "Remove duplicate lines from any list, find duplicates only, sort A→Z or Z→A, or remove empty lines.",
    category: "text",
    icon: ListFilter,
    component: RemoveDuplicateLines,
    keywords: ["remove duplicates", "dedupe lines", "unique lines", "sort lines"],
    related: ["whitespace-cleaner", "word-counter"],
    howToUse: ["Paste your list of lines.", "Pick an operation.", "The output and the number of removed lines appear instantly."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "whitespace-cleaner",
    name: "Whitespace Cleaner",
    short: "Trim, collapse, and normalize text spacing",
    description: "Clean text by trimming each line, collapsing spaces, removing blank lines, normalizing line endings, and more.",
    category: "text",
    icon: Eraser,
    component: WhitespaceCleaner,
    keywords: ["trim whitespace", "remove spaces", "clean text", "normalize text"],
    related: ["remove-duplicate-lines", "word-counter"],
    howToUse: ["Paste text with messy whitespace.", "Toggle the cleaning options you want.", "Output updates live and shows how many characters were removed."],
    faqs: FAQ_TEXT,
  },

  // ───────── Developer ─────────
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    short: "Beautify, minify, and validate JSON instantly",
    description: "Format, minify, and validate JSON with adjustable indentation. Errors are highlighted with helpful messages.",
    category: "developer",
    icon: Braces,
    component: JsonFormatter,
    isPopular: true,
    featured: true,
    keywords: ["json formatter", "json beautifier", "json minifier", "json validator"],
    related: ["base64-encoder", "csv-json-converter", "jwt-decoder"],
    howToUse: ["Paste your JSON.", "Pick Beautify, Minify, or Validate.", "Choose indent (2 sp, 4 sp, or Tab) for beautify."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "base64-encoder",
    name: "Base64 Encoder / Decoder",
    short: "Encode text to Base64 or decode it back",
    description: "Encode text to Base64 or decode Base64 back to UTF-8 text. Fully client-side — your data never leaves your browser.",
    category: "developer",
    icon: ArrowDownToLine,
    component: Base64Encoder,
    isPopular: true,
    keywords: ["base64", "encode", "decode", "utf-8"],
    related: ["url-encoder", "html-entity-encoder", "hash-generator"],
    howToUse: ["Paste your text or Base64 string.", "Switch between Encode and Decode mode.", "Output updates live."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    short: "encodeURIComponent, encodeURI, decodeURIComponent",
    description: "Encode or decode URLs using encodeURIComponent, encodeURI, or decodeURIComponent.",
    category: "developer",
    icon: Link2,
    component: UrlEncoder,
    keywords: ["url encode", "url decode", "percent encoding", "uri"],
    related: ["base64-encoder", "html-entity-encoder"],
    howToUse: ["Paste your text or URL-encoded string.", "Pick the function you want.", "Output updates live."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    short: "Decode JSON Web Tokens to inspect header & payload",
    description: "Decode a JSON Web Token (JWT) to inspect its header, payload, claims, and expiration. Decoding is client-side; signature verification requires server-side logic.",
    category: "developer",
    icon: Key,
    component: JwtDecoder,
    keywords: ["jwt", "json web token", "decode jwt", "inspect token"],
    related: ["base64-encoder", "json-formatter"],
    howToUse: ["Paste your JWT.", "Header, payload, and claims are decoded instantly.", "Expiration status is shown if the token includes an exp claim."],
    faqs: [
      ...FAQ_TEXT,
      { q: "Does this verify the token's signature?", a: "No. Decoding only reads the payload — anyone could craft a token with any payload. Always verify signatures server-side before trusting a token's contents." },
    ],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    short: "SHA-1, SHA-256, SHA-384, SHA-512 hashes",
    description: "Generate SHA-1, SHA-256, SHA-384, and SHA-512 hashes in real time using the browser's Web Crypto API.",
    category: "developer",
    icon: Hash,
    component: HashGenerator,
    keywords: ["sha", "hash", "checksum", "sha-256", "sha-512"],
    related: ["uuid-generator", "base64-encoder"],
    howToUse: ["Type any text.", "All four hashes are computed and displayed.", "Click Copy next to any hash to copy it."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    short: "Generate UUID v4 and v7 in bulk",
    description: "Generate one or many UUIDs in version 4 (random) or version 7 (time-ordered, RFC 9562) formats.",
    category: "developer",
    icon: Fingerprint,
    component: UuidGenerator,
    keywords: ["uuid", "guid", "v4", "v7", "rfc 9562"],
    related: ["hash-generator", "password-generator"],
    howToUse: ["Choose count (1–500), version (v4 or v7), and case.", "Click Generate.", "Copy a single UUID or all of them."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    short: "HEX, RGB, HSL, HSV, CMYK + contrast",
    description: "Convert colors between HEX, RGB, HSL, HSV, and CMYK, with WCAG contrast ratios for white and black text.",
    category: "developer",
    icon: Palette,
    component: ColorConverter,
    isPopular: true,
    keywords: ["color converter", "hex to rgb", "rgb to hsl", "color palette", "wcag contrast"],
    related: ["color-palette-generator", "gradient-generator"],
    howToUse: ["Pick a color or type a hex code.", "All formats update instantly with copy buttons.", "Accessibility shows contrast on white/black backgrounds."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "html-entity-encoder",
    name: "HTML Entity Encoder",
    short: "Encode & decode HTML entities, escape JS strings",
    description: "Encode and decode HTML entities, or escape and unescape JavaScript string literals.",
    category: "developer",
    icon: Code2,
    component: HtmlEntityEncoder,
    keywords: ["html entities", "html encode", "html decode", "escape strings", "javascript escape"],
    related: ["url-encoder", "base64-encoder"],
    howToUse: ["Paste your text.", "Pick Encode, Decode, Escape (JS string), or Unescape.", "Output updates live."],
    faqs: FAQ_TEXT,
  },

  // ───────── Converters ─────────
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    short: "Binary, octal, decimal, hexadecimal",
    description: "Convert numbers between binary (base 2), octal (base 8), decimal (base 10), and hexadecimal (base 16). Supports arbitrarily large integers via BigInt.",
    category: "converters",
    icon: BinIcon,
    component: NumberBaseConverter,
    keywords: ["binary", "decimal", "hexadecimal", "octal", "number base"],
    related: ["roman-numeral-converter", "timestamp-converter"],
    howToUse: ["Type a value in any of the four bases.", "All other bases update automatically."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    short: "Length, weight, temperature, volume, speed, data, time",
    description: "Convert between units across 7 categories: length, weight, temperature, volume, speed, data size, and time.",
    category: "converters",
    icon: BookOpen,
    component: UnitConverter,
    isPopular: true,
    featured: true,
    keywords: ["unit converter", "length", "weight", "temperature", "volume", "speed", "data size", "time"],
    related: ["number-base-converter", "timestamp-converter"],
    howToUse: ["Pick a category.", "Pick the From and To units.", "Type a value to convert instantly."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "roman-numeral-converter",
    name: "Roman Numeral Converter",
    short: "Numbers ↔ Roman numerals (I–MMMCMXCIX)",
    description: "Convert between Arabic numbers and Roman numerals. Supports the standard range 1 to 3999.",
    category: "converters",
    icon: Hash,
    component: RomanNumeralConverter,
    keywords: ["roman numerals", "numerals", "roman numerals converter", "arabic to roman"],
    related: ["number-base-converter", "timestamp-converter"],
    howToUse: ["Pick → Roman or → Number.", "Type a value.", "Result updates live."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "csv-json-converter",
    name: "CSV ↔ JSON Converter",
    short: "Convert CSV to JSON and back",
    description: "Convert CSV data (with header row) to a JSON array, or convert a JSON array of objects to CSV.",
    category: "converters",
    icon: ListFilter,
    component: CsvJsonConverter,
    keywords: ["csv to json", "json to csv", "csv converter", "table data"],
    related: ["json-formatter", "base64-encoder"],
    howToUse: ["Pick CSV → JSON or JSON → CSV.", "Paste your data.", "Result includes a copy and download button."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    short: "Unix timestamp ↔ human-readable date",
    description: "Convert a Unix timestamp (seconds or milliseconds) to a UTC, local, and ISO date — or convert a date string into a timestamp.",
    category: "converters",
    icon: Clock,
    component: TimestampConverter,
    keywords: ["unix timestamp", "epoch converter", "timestamp to date", "iso 8601"],
    related: ["unit-converter", "number-base-converter"],
    howToUse: ["Pick → Date or → Timestamp.", "Type a value.", "All formats appear instantly."],
    faqs: FAQ_TEXT,
  },

  // ───────── Calculators ─────────
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    short: "What is X% of Y, % change, and more",
    description: "Four percentage modes: what is X% of Y, X is what % of Y, percentage change, and add X% to Y.",
    category: "calculators",
    icon: Calculator,
    component: PercentageCalculator,
    isPopular: true,
    featured: true,
    keywords: ["percentage", "percent change", "percentage of", "percent increase"],
    related: ["compound-interest-calculator", "tip-calculator"],
    howToUse: ["Pick the calculation type.", "Enter both values.", "Result appears instantly."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    short: "Exact age in years, months, days",
    description: "Calculate exact age in years, months, and days from a birth date, plus totals in months, weeks, days, hours, and minutes.",
    category: "calculators",
    icon: Activity,
    component: AgeCalculator,
    keywords: ["age calculator", "birthday", "date difference", "how old"],
    related: ["timestamp-converter", "bmi-calculator"],
    howToUse: ["Enter your birth date.", "Optionally change the target date (defaults to today).", "Exact age and totals appear instantly."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    short: "Body Mass Index in metric or imperial",
    description: "Calculate Body Mass Index (BMI) using metric or imperial units, with category label and reference table.",
    category: "calculators",
    icon: Activity,
    component: BmiCalculator,
    keywords: ["bmi", "body mass index", "healthy weight", "bmi calculator"],
    related: ["age-calculator", "percentage-calculator"],
    howToUse: ["Pick metric or imperial.", "Enter weight and height.", "BMI and category appear instantly."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "loan-calculator",
    name: "Loan / EMI Calculator",
    short: "Monthly payment, interest, and total",
    description: "Calculate monthly loan payments (EMI), total interest, and total paid using the standard amortization formula.",
    category: "calculators",
    icon: Landmark,
    component: LoanCalculator,
    keywords: ["loan calculator", "emi", "mortgage", "monthly payment", "interest"],
    related: ["compound-interest-calculator", "percentage-calculator"],
    howToUse: ["Enter the principal, annual interest rate, and tenure in years.", "Monthly payment and totals appear instantly."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    short: "Tip, total, and split per person",
    description: "Calculate tip and total, split a bill between any number of people, with quick tip presets and optional round-up.",
    category: "calculators",
    icon: Receipt,
    component: TipCalculator,
    keywords: ["tip calculator", "split bill", "restaurant tip", "gratuity"],
    related: ["percentage-calculator", "loan-calculator"],
    howToUse: ["Enter bill amount, tip percentage, and number of people.", "Optionally round up each share.", "Tip and per-person amounts update live."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    short: "Future value with optional contributions",
    description: "Estimate the future value of an investment using compound interest, with optional recurring monthly or yearly contributions.",
    category: "calculators",
    icon: TrendingUp,
    component: CompoundInterestCalculator,
    keywords: ["compound interest", "investment calculator", "future value", "savings"],
    related: ["loan-calculator", "percentage-calculator"],
    howToUse: ["Enter principal, annual rate, and years.", "Pick compounding frequency.", "Optionally add a recurring contribution.", "Future value and interest appear instantly."],
    faqs: FAQ_TEXT,
  },

  // ───────── Generators ─────────
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    short: "Customizable QR codes with download",
    description: "Generate QR codes for URLs, contact info, WiFi credentials, and more — with custom colors, sizes, and error-correction levels.",
    category: "generators",
    icon: QrCode,
    component: QrCodeGenerator,
    isPopular: true,
    featured: true,
    keywords: ["qr code", "qr generator", "qrcode", "wifi qr"],
    related: ["password-generator", "meta-tag-generator"],
    howToUse: ["Type the content to encode (URL, text, WiFi, vCard…).", "Customize colors, size, and error correction.", "Download as PNG or copy the data URL."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    short: "Strong, secure passwords using crypto RNG",
    description: "Generate strong random passwords using cryptographically-secure randomness, with configurable length, character sets, and strength meter.",
    category: "generators",
    icon: KeyRound,
    component: PasswordGenerator,
    isPopular: true,
    keywords: ["password generator", "strong password", "random password", "secure password"],
    related: ["uuid-generator", "qr-code-generator"],
    howToUse: ["Pick length and character sets.", "Avoid similar-looking characters if needed.", "Regenerate or copy your password."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    short: "Analogous, complementary, triadic & more",
    description: "Generate harmonious color palettes in 5 schemes: analogous, complementary, triadic, tetradic, and monochromatic.",
    category: "generators",
    icon: Palette,
    component: ColorPaletteGenerator,
    keywords: ["color palette", "color scheme", "analogous", "complementary", "triadic"],
    related: ["color-converter", "gradient-generator"],
    howToUse: ["Pick a base hue.", "Choose a color scheme.", "Click any swatch to copy its hex code."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "gradient-generator",
    name: "CSS Gradient Generator",
    short: "Linear & radial gradients with multiple stops",
    description: "Design linear or radial CSS gradients with multiple color stops, then copy the generated CSS in one click.",
    category: "generators",
    icon: Paintbrush,
    component: GradientGenerator,
    keywords: ["css gradient", "gradient generator", "linear gradient", "radial gradient"],
    related: ["color-palette-generator", "color-converter"],
    howToUse: ["Pick a direction (linear or radial).", "Add or adjust color stops.", "Copy the generated CSS."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    short: "SEO + Open Graph + Twitter meta tags",
    description: "Generate title, description, keywords, canonical, Open Graph, and Twitter meta tags for any page.",
    category: "generators",
    icon: Tags,
    component: MetaTagGenerator,
    keywords: ["meta tags", "seo meta", "html head", "open graph", "twitter cards"],
    related: ["open-graph-generator", "robots-txt-generator"],
    howToUse: ["Fill in your page's title, description, URL, image, and Twitter handle.", "Copy the generated meta tags into your <head>."],
    faqs: FAQ_TEXT,
  },

  // ───────── Web & SEO ─────────
  {
    slug: "open-graph-generator",
    name: "Open Graph Generator",
    short: "OG tags with live social preview",
    description: "Generate Open Graph tags with a live preview of how your page will look when shared on social platforms.",
    category: "web-seo",
    icon: Share2,
    component: OpenGraphGenerator,
    keywords: ["open graph", "og tags", "social preview", "share preview"],
    related: ["meta-tag-generator", "robots-txt-generator"],
    howToUse: ["Fill in title, description, URL, and image.", "See the live preview as you type.", "Copy the OG tags into your <head>."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "robots-txt-generator",
    name: "robots.txt Generator",
    short: "Crawl rules per user-agent + sitemap",
    description: "Generate a robots.txt file with per-user-agent rules, allow/disallow patterns, crawl-delay, and a sitemap directive.",
    category: "web-seo",
    icon: Bot,
    component: RobotsTxtGenerator,
    keywords: ["robots.txt", "crawler rules", "seo", "sitemap"],
    related: ["meta-tag-generator", "open-graph-generator"],
    howToUse: ["Add one or more rules per user-agent.", "Specify Allow and Disallow paths (one per line).", "Add a sitemap URL and optional crawl-delay.", "Download or copy the file."],
    faqs: FAQ_TEXT,
  },

  // ───────── AI ─────────
  {
    slug: "ai-summarizer",
    name: "AI Summarizer",
    short: "Concise, bullets, or key-points summaries",
    description: "Summarize long text into concise paragraphs, bullet points, or key-point lists. Choose short, medium, or detailed length.",
    category: "ai",
    icon: Wand2,
    component: AiSummarizer,
    isAI: true,
    isNew: true,
    featured: true,
    keywords: ["ai summarizer", "text summarizer", "summary generator", "summarize article"],
    related: ["ai-grammar", "ai-rewriter", "ai-translator"],
    howToUse: ["Paste the text you want to summarize.", "Pick a style (concise, bullets, key-points) and length.", "Click Summarize."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "ai-grammar",
    name: "AI Grammar Improver",
    short: "Fix grammar, spelling & clarity",
    description: "Improve grammar, spelling, punctuation, and clarity while preserving your meaning and tone — with optional tone overrides.",
    category: "ai",
    icon: SpellCheck,
    component: AiGrammar,
    isAI: true,
    isNew: true,
    keywords: ["ai grammar", "grammar check", "spell check", "improve writing"],
    related: ["ai-summarizer", "ai-rewriter", "ai-translator"],
    howToUse: ["Paste your text.", "Pick a tone (neutral, professional, casual, or academic).", "Click Improve grammar."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "ai-rewriter",
    name: "AI Rewriter",
    short: "Paraphrase text in 5 styles",
    description: "Paraphrase your text in five styles: simpler, formal, concise, expanded, or persuasive — without changing the meaning.",
    category: "ai",
    icon: PenLine,
    component: AiRewriter,
    isAI: true,
    isNew: true,
    keywords: ["ai rewriter", "paraphrase", "rewrite text", "rephrase"],
    related: ["ai-summarizer", "ai-grammar", "ai-translator"],
    howToUse: ["Paste your text.", "Pick a style (simpler, formal, concise, expand, or persuasive).", "Click Rewrite."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "ai-translator",
    name: "AI Translator",
    short: "Translate between 20+ languages",
    description: "Translate text between 20+ languages while preserving meaning, names, numbers, and tone.",
    category: "ai",
    icon: Languages,
    component: AiTranslator,
    isAI: true,
    isNew: true,
    keywords: ["ai translator", "machine translation", "translate text", "language translator"],
    related: ["ai-summarizer", "ai-grammar", "ai-rewriter"],
    howToUse: ["Pick source and target languages.", "Paste your text.", "Click Translate."],
    faqs: FAQ_TEXT,
  },
  {
    slug: "ai-code-explainer",
    name: "AI Code Explainer",
    short: "Plain-language explanations of any code",
    description: "Paste any code snippet and the AI will explain what it does, how it works, inputs and outputs, and edge cases — in plain language.",
    category: "ai",
    icon: Code2,
    component: AiCodeExplainer,
    isAI: true,
    isNew: true,
    keywords: ["ai code explainer", "explain code", "code analysis", "code walkthrough"],
    related: ["json-formatter", "jwt-decoder", "hash-generator"],
    howToUse: ["Paste your code.", "Optionally set the language and detail level.", "Click Explain code."],
    faqs: FAQ_TEXT,
  },
];

// ── Lookup helpers ─────────────────────────────────────────────────────────
export const toolsBySlug = new Map(tools.map((t) => [t.slug, t]));
export const toolsByCategory = (slug: string) => tools.filter((t) => t.category === slug);
export const featuredTools = () => tools.filter((t) => t.featured);
export const popularTools = () => tools.filter((t) => t.isPopular);
export const newTools = () => tools.filter((t) => t.isNew);
